import type { Metadata } from"next";
import { Geist, Geist_Mono } from"next/font/google";
import"./globals.css";
import Navigation from"@/components/Navigation";
import GlobalModalManager from"@/components/GlobalModalManager";
import { Suspense } from"react";
import { createClient } from"@/utils/supabase/server";

const geistSans = Geist({
  variable:"--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable:"--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title:"Create Next App",
  description:"Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  
  let userRole = null
  if (user) {
    const { data: profile } = await supabase.from('profiles').select('household_role').eq('id', user.id).single()
    userRole = profile?.household_role
  }

  const { data: students } = await supabase.from('students').select('*')
  const { data: subjects } = await supabase.from('subjects').select('*').order('name')
  const { data: activities } = await supabase.from('activities').select('*').order('name')

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navigation students={students || []} userRole={userRole}>
          {children}
          <Suspense fallback={null}>
            <GlobalModalManager students={students || []} subjects={subjects || []} activities={activities || []} />
          </Suspense>
        </Navigation>
      </body>
    </html>
  );
}
